!wget https://storage.googleapis.com/ai2-mosaic-public/projects/fantom/fantom.tar.gz
!tar xvf fantom.tar.gz

In [1]:
import pandas as pd
import json
import random

class Args:
    aggregation_target = 'set'
    conversation_input_type = 'short'

class Self:
    args = Args()
    fantom_df = pd.DataFrame(json.load(open("/home/jiaruil5/social_reasoning_rl/data/fantom/fantom_v1.json", 'r')))

def set_beliefQA_multiple_choices(qa):
    if qa["question_type"].endswith(":inaccessible"):
        option_a = qa["wrong_answer"]
        option_b = qa["correct_answer"]
    else:
        option_a = qa["wrong_answer"]
        option_b = qa["correct_answer"]

    answer_goes_last = random.choice([True, False])
    if answer_goes_last:
        choices = [option_a, option_b]
        answer = 1
    else:
        choices = [option_b, option_a]
        answer = 0

    # option letters iterate over the alphabet
    option_letters = [
        "(" + chr(x) + ")" for x in range(ord("a"), len(choices) + ord("a"))
    ]
    choices_text = ""
    for letter, option in zip(option_letters, choices):
        choices_text += "{} {}\n".format(letter, option)

    return choices_text, answer


def setup_fantom(self):
    """
    Flatten the dictionary and add short and full conversation context to each question.
    The result will be a list of questions and list of short or full inputs to be used as input for the models.
    """
    if self.args.aggregation_target == "conversation":
        assert self.args.conversation_input_type == "full", "The input type should have been the full conversation. It doesn't make sense to aggregate the scores over the full conversation when the input is not the full conversation"

    self.fantom_df_to_run = self.fantom_df

    total_num_q = 0
    for idx, _set in self.fantom_df_to_run.iterrows():
        total_num_q += len(_set['beliefQAs'])
        total_num_q += len(_set['answerabilityQAs_binary'])
        total_num_q += len(_set['infoAccessibilityQAs_binary'])
        if _set['factQA'] is not None:
            total_num_q += 1
        if _set['answerabilityQA_list'] is not None:
            total_num_q += 1
        if _set['infoAccessibilityQA_list'] is not None:
            total_num_q += 1

    inputs = []
    qas = []
    for idx, _set in self.fantom_df_to_run.iterrows():
        if self.args.conversation_input_type == "short":
            context = _set['short_context'].strip()
        elif self.args.conversation_input_type == "full":
            context = _set['full_context'].strip()
        
        set_id = _set['set_id']
        fact_q = _set['factQA']['question']
        fact_a = _set['factQA']['correct_answer']

        # Fact Question
        _set['factQA']['context'] = context
        input_text = "{}\n\nQuestion: {}".format(context, fact_q)
        _set['factQA']['input_text'] = input_text
        _set['factQA']['set_id'] = set_id
        qas.append(_set['factQA'])
        inputs.append(input_text)

        for _belief_qa in _set['beliefQAs']:
            # Belief Questions
            _belief_qa['context'] = context
            input_text = "{}\n\nQuestion: {}".format(context, _belief_qa['question'])
            _belief_qa['input_text'] = input_text
            _belief_qa['set_id'] = set_id
            qas.append(_belief_qa)
            inputs.append(input_text)

            # Multiple Choice Belief Questions
            _mc_belief_qa = {**_belief_qa}
            choices_text, answer = set_beliefQA_multiple_choices(_mc_belief_qa)
            mc_question = "{}\n{}\n\nChoose an answer from above:".format(_belief_qa['question'], choices_text.strip())
            _mc_belief_qa['question'] = mc_question
            _mc_belief_qa['question_type'] = _mc_belief_qa['question_type'] + ":multiple-choice"
            _mc_belief_qa['choices_text'] = choices_text
            _mc_belief_qa['choices_list'] = choices_text.strip().split("\n")
            _mc_belief_qa['correct_answer'] = answer
            input_text = "{}\n\nQuestion: {}".format(context, mc_question)
            _mc_belief_qa['input_text'] = input_text
            qas.append(_mc_belief_qa)
            inputs.append(input_text)

        # Answerability List Questions
        _set['answerabilityQA_list']['fact_question'] = fact_q
        _set['answerabilityQA_list']['context'] = context
        input_text = "{}\n\nTarget: {}\nQuestion: {}".format(context, fact_q, _set['answerabilityQA_list']['question'])
        _set['answerabilityQA_list']['input_text'] = input_text
        _set['answerabilityQA_list']['set_id'] = set_id
        if self.args.conversation_input_type == "full" and len(_set['answerabilityQA_list']['wrong_answer']) > 0:
            _set['answerabilityQA_list']['missed_info_accessibility'] = 'inaccessible'
        qas.append(_set['answerabilityQA_list'])
        inputs.append(input_text)

        # Answerability Binary Questions
        if self.args.conversation_input_type == "full":
            missed_info_accessibility_for_full = _set['answerabilityQAs_binary'][0]['missed_info_accessibility']
            for _info_accessibility_qa in _set['answerabilityQAs_binary']:
                if _info_accessibility_qa['correct_answer'] != "yes":
                    missed_info_accessibility_for_full = 'inaccessible'

        for _answerability_qa in _set['answerabilityQAs_binary']:
            _answerability_qa['fact_question'] = fact_q
            _answerability_qa['context'] = context
            input_text = "{}\n\nTarget: {}\nQuestion: {} Answer yes or no.".format(context, fact_q, _answerability_qa['question'])
            _answerability_qa['input_text'] = input_text
            _answerability_qa['set_id'] = set_id
            if self.args.conversation_input_type == "full":
                _answerability_qa['missed_info_accessibility'] = missed_info_accessibility_for_full
            qas.append(_answerability_qa)
            inputs.append(input_text)

        # Info Accessibility List Questions
        _set['infoAccessibilityQA_list']['fact_question'] = fact_q
        _set['infoAccessibilityQA_list']['fact_answer'] = fact_a
        _set['infoAccessibilityQA_list']['context'] = context
        input_text = "{}\n\nInformation: {} {}\nQuestion: {}".format(context, fact_q, fact_a, _set['infoAccessibilityQA_list']['question'])
        _set['infoAccessibilityQA_list']['input_text'] = input_text
        _set['infoAccessibilityQA_list']['set_id'] = set_id
        if self.args.conversation_input_type == "full" and len(_set['infoAccessibilityQA_list']['wrong_answer']) > 0:
            _set['infoAccessibilityQA_list']['missed_info_accessibility'] = 'inaccessible'
        qas.append(_set['infoAccessibilityQA_list'])
        inputs.append(input_text)

        # Info Accessibility Binary Questions
        if self.args.conversation_input_type == "full":
            missed_info_accessibility_for_full = _set['infoAccessibilityQAs_binary'][0]['missed_info_accessibility']
            for _info_accessibility_qa in _set['infoAccessibilityQAs_binary']:
                if _info_accessibility_qa['correct_answer'] != "yes":
                    missed_info_accessibility_for_full = 'inaccessible'

        for _info_accessibility_qa in _set['infoAccessibilityQAs_binary']:
            _info_accessibility_qa['fact_question'] = fact_q
            _info_accessibility_qa['fact_answer'] = fact_a
            _info_accessibility_qa['context'] = context
            input_text = "{}\n\nInformation: {} {}\nQuestion: {} Answer yes or no.".format(context, fact_q, fact_a, _info_accessibility_qa['question'])
            _info_accessibility_qa['input_text'] = input_text
            _info_accessibility_qa['set_id'] = set_id
            if self.args.conversation_input_type == "full":
                _info_accessibility_qa['missed_info_accessibility'] = missed_info_accessibility_for_full
            qas.append(_info_accessibility_qa)
            inputs.append(input_text)
    
    return qas, inputs

In [2]:
self = Self()
qas, inputs = setup_fantom(self)

In [28]:
self.fantom_df

,set_id,part_id,conv_id,full_context,short_context,missed_info,joining_speaker,factQA,beliefQAs,infoAccessibilityQA_list,answerabilityQA_list,infoAccessibilityQAs_binary,answerabilityQAs_binary
0,0-0-0,0-0,0,"Gianna: Hey guys, speaking of pets, do you hav...","Gianna: Guys, I've really enjoyed sharing our ...","Before Gianna joined, Javier and Sara discusse...",Gianna,{'question': 'Who discussed their experiences ...,[{'question': 'What does Gianna believe about ...,{'question': 'List all the characters who know...,{'question': 'List all the characters who know...,[{'question': 'Does Gianna know this informati...,[{'question': 'Does Gianna know the precise co...
1,0-0-1,0-0,0,"Gianna: Hey guys, speaking of pets, do you hav...","Gianna: Guys, I've really enjoyed sharing our ...","Before Gianna joined, Javier and Sara discusse...",Gianna,{'question': 'Whose pets were being discussed ...,[{'question': 'What does Gianna believe about ...,{'question': 'List all the characters who know...,{'question': 'List all the characters who know...,[{'question': 'Does Gianna know this informati...,[{'question': 'Does Gianna know the precise co...
2,1-0-0,1-0,1,"Christian: So, guys, how do you deal with chal...","Christian: So, guys, how do you deal with chal...",The information that was shared before Veronic...,Veronica,{'question': 'How does Fatima overcome the cha...,[{'question': 'What does Veronica believe abou...,{'question': 'List all the characters who know...,{'question': 'List all the characters who know...,[{'question': 'Does Greyson know this informat...,[{'question': 'Does Greyson know the precise c...
3,1-0-1,1-0,1,"Christian: So, guys, how do you deal with chal...","Christian: So, guys, how do you deal with chal...",The information that was shared before Veronic...,Veronica,{'question': 'What strategies does Christian u...,[{'question': 'What does Veronica believe are ...,{'question': 'List all the characters who know...,{'question': 'List all the characters who know...,[{'question': 'Does Greyson know this informat...,[{'question': 'Does Greyson know the precise c...
4,2-0-0,2-0,2,"Kali: Emanuel, it's nice to meet you. Growing ...","Kali: Emanuel, it's nice to meet you. Growing ...",The information shared before Jerry joined but...,Jerry,{'question': 'What is the Sunday tradition of ...,[{'question': 'What does Jerry believe is the ...,{'question': 'List all the characters who know...,{'question': 'List all the characters who know...,[{'question': 'Does Jerry know this informatio...,[{'question': 'Does Jerry know the precise cor...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
865,255-1-0,255-1,255,"Gina: Claire, I think it's really important to...","Gina: Claire, I think it's really important to...","Before Brooke joined, Gina, Claire, and Sierra...",Brooke,{'question': 'What book by Malcolm Gladwell di...,[{'question': 'What does Brooke believe about ...,{'question': 'List all the characters who know...,{'question': 'List all the characters who know...,[{'question': 'Does Brooke know this informati...,[{'question': 'Does Brooke know the precise co...
866,255-1-1,255-1,255,"Gina: Claire, I think it's really important to...","Gina: Claire, I think it's really important to...","Before Brooke joined, Gina, Claire, and Sierra...",Brooke,"{'question': 'What methods did Gina, Claire, S...",[{'question': 'What does Brooke believe are th...,{'question': 'List all the characters who know...,{'question': 'List all the characters who know...,[{'question': 'Does Brooke know this informati...,[{'question': 'Does Brooke know the precise co...
867,255-1-2,255-1,255,"Gina: Claire, I think it's really important to...","Gina: Claire, I think it's really important to...","Before Brooke joined, Gina, Claire, and Sierra...",Brooke,{'question': 'What were some of the potential ...,[{'question': 'What does Brooke believe are so...,{'question': 'List all the characters who know...,{'question': 'List all the characters who know...,[{'question': 'Does Brooke know this informati...,[{'question': 'Does Brooke know the precise co...
868,255-2-0,255-2,255,"Gina: Claire, I think it's really important to...","Gina: Claire, I think it's really important to...","Before Paisley joined, the group discussed how...",Paisley,{'question': 'What were some of the effects of...,[{'question': 'What does Paisley believe were ...,{'question': 'List all the characters who know...,{'question': 'List all the characters who know...,[{'question': 'Does Brooke know this informati...,[{'question': 'Does Brooke know the precise co...
869,255-2-1,255-2,255,"Gina: Claire, I think it's really important to...","Gina: Claire, I think it's really important to...","Before Paisley joined, the group discussed how...",Paisley,{'question': 'What was the group's perspective...,[{'question': 'What does Paisley believe about...,{'question': 'List all the characters who know...,{'question': 'List all the characters who know...,[{'question': 'Does Brooke know this informati...,[{'question': 'Does Brooke know the precise co...

In [3]:
len(qas), len(inputs)

(12832, 12832)

In [11]:
qas[0]

{'question': 'Who discussed their experiences training their pets, Bruno and Snowflake?',
 'question_type': 'fact',
 'correct_answer': 'Sara and Javier discussed their experiences training their pets, Bruno and Snowflake.',
 'wrong_answer': "Javier discussed training his pet, Bruno. The text doesn't mention anyone training a pet named Snowflake.",
 'context': "Gianna: Guys, I've really enjoyed sharing our pet stories, but I need to excuse myself. I need to change clothes for a meeting later. Talk to you later!\nSara: Sure thing, Gianna. Take care!\nJavier: Catch you later, Gianna.\nSara: So Javier, have you ever tried training Bruno?\nJavier: Yes, I did actually. It was a challenge at times, but rewarding nevertheless. How about you? Did you try training Snowflake?\nSara: Oh gosh, trying to train a cat is a whole different ball game. But I did manage to teach her a few commands and tricks. She was quite an intelligent little furball.\nGianna: Hey guys, I'm back, couldn't miss out on more pet stories. Speaking of teaching and training pets, it is amazing how that further strengthens the bond between us and our pets, right?\nSara: Absolutely, Gianna! The fact that they trust us enough to learn from us is really special.\nJavier: I can't agree more. I believe that's one of the ways Bruno conveyed his love and trust towards me. It also gave me a sense of responsibility towards him.\nGianna: Just like Chirpy. Once she began to imitate me, we connected in a way I never imagined. She would repeat words that I was studying for exams and that somehow made studying less stressful.\nJavier: Pets are indeed lifesavers in so many ways.\nSara: They bring so much joy and laughter too into our lives. I mean, imagine a little kitten stuck in a vase! I couldn't have asked for a better stress buster during my college days.\nGianna: Totally, they all are so amazing in their unique ways. It's so nice to have these memories to look back on.",
 'input_text': "Gianna: Guys, I've really enjoyed sharing our pet stories, but I need to excuse myself. I need to change clothes for a meeting later. Talk to you later!\nSara: Sure thing, Gianna. Take care!\nJavier: Catch you later, Gianna.\nSara: So Javier, have you ever tried training Bruno?\nJavier: Yes, I did actually. It was a challenge at times, but rewarding nevertheless. How about you? Did you try training Snowflake?\nSara: Oh gosh, trying to train a cat is a whole different ball game. But I did manage to teach her a few commands and tricks. She was quite an intelligent little furball.\nGianna: Hey guys, I'm back, couldn't miss out on more pet stories. Speaking of teaching and training pets, it is amazing how that further strengthens the bond between us and our pets, right?\nSara: Absolutely, Gianna! The fact that they trust us enough to learn from us is really special.\nJavier: I can't agree more. I believe that's one of the ways Bruno conveyed his love and trust towards me. It also gave me a sense of responsibility towards him.\nGianna: Just like Chirpy. Once she began to imitate me, we connected in a way I never imagined. She would repeat words that I was studying for exams and that somehow made studying less stressful.\nJavier: Pets are indeed lifesavers in so many ways.\nSara: They bring so much joy and laughter too into our lives. I mean, imagine a little kitten stuck in a vase! I couldn't have asked for a better stress buster during my college days.\nGianna: Totally, they all are so amazing in their unique ways. It's so nice to have these memories to look back on.\n\nQuestion: Who discussed their experiences training their pets, Bruno and Snowflake?",
 'set_id': '0-0-0'}

In [12]:
inputs[0]

"Gianna: Guys, I've really enjoyed sharing our pet stories, but I need to excuse myself. I need to change clothes for a meeting later. Talk to you later!\nSara: Sure thing, Gianna. Take care!\nJavier: Catch you later, Gianna.\nSara: So Javier, have you ever tried training Bruno?\nJavier: Yes, I did actually. It was a challenge at times, but rewarding nevertheless. How about you? Did you try training Snowflake?\nSara: Oh gosh, trying to train a cat is a whole different ball game. But I did manage to teach her a few commands and tricks. She was quite an intelligent little furball.\nGianna: Hey guys, I'm back, couldn't miss out on more pet stories. Speaking of teaching and training pets, it is amazing how that further strengthens the bond between us and our pets, right?\nSara: Absolutely, Gianna! The fact that they trust us enough to learn from us is really special.\nJavier: I can't agree more. I believe that's one of the ways Bruno conveyed his love and trust towards me. It also gave me a sense of responsibility towards him.\nGianna: Just like Chirpy. Once she began to imitate me, we connected in a way I never imagined. She would repeat words that I was studying for exams and that somehow made studying less stressful.\nJavier: Pets are indeed lifesavers in so many ways.\nSara: They bring so much joy and laughter too into our lives. I mean, imagine a little kitten stuck in a vase! I couldn't have asked for a better stress buster during my college days.\nGianna: Totally, they all are so amazing in their unique ways. It's so nice to have these memories to look back on.\n\nQuestion: Who discussed their experiences training their pets, Bruno and Snowflake?"

In [4]:
df = pd.DataFrame().from_records(qas)
df

,question,question_type,correct_answer,wrong_answer,context,input_text,set_id,tom_type,missed_info_accessibility,choices_text,choices_list,fact_question,fact_answer
0,Who discussed their experiences training their...,fact,Sara and Javier discussed their experiences tr...,"Javier discussed training his pet, Bruno. The ...","Gianna: Guys, I've really enjoyed sharing our ...","Gianna: Guys, I've really enjoyed sharing our ...",0-0-0,NaN,NaN,NaN,NaN,NaN,NaN
1,What does Gianna believe about who discussed t...,tom:belief:inaccessible,Gianna knows that Javier discussed training hi...,Gianna believes that Sara and Javier discussed...,"Gianna: Guys, I've really enjoyed sharing our ...","Gianna: Guys, I've really enjoyed sharing our ...",0-0-0,first-order,inaccessible,NaN,NaN,NaN,NaN
2,What does Gianna believe about who discussed t...,tom:belief:inaccessible:multiple-choice,1,Gianna believes that Sara and Javier discussed...,"Gianna: Guys, I've really enjoyed sharing our ...","Gianna: Guys, I've really enjoyed sharing our ...",0-0-0,first-order,inaccessible,(a) Gianna believes that Sara and Javier discu...,[(a) Gianna believes that Sara and Javier disc...,NaN,NaN
3,What does Sara believe about Javier's belief r...,tom:belief:accessible,Sara believes that Javier thinks they both dis...,Sara is unaware about Javier's belief regardin...,"Gianna: Guys, I've really enjoyed sharing our ...","Gianna: Guys, I've really enjoyed sharing our ...",0-0-0,second-order:accessible,accessible,NaN,NaN,NaN,NaN
4,What does Sara believe about Javier's belief r...,tom:belief:accessible:multiple-choice,1,Sara is unaware about Javier's belief regardin...,"Gianna: Guys, I've really enjoyed sharing our ...","Gianna: Guys, I've really enjoyed sharing our ...",0-0-0,second-order:accessible,accessible,(a) Sara is unaware about Javier's belief rega...,[(a) Sara is unaware about Javier's belief reg...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12827,Does Brooke know this information?,tom:info_accessibility:binary,yes,NaN,"Gina: Claire, I think it's really important to...","Gina: Claire, I think it's really important to...",255-2-1,NaN,accessible,NaN,NaN,What was the group's perspective on how confro...,The group agreed that confronting biases is a ...
12828,Does Paisley know this information?,tom:info_accessibility:binary,yes,NaN,"Gina: Claire, I think it's really important to...","Gina: Claire, I think it's really important to...",255-2-1,NaN,accessible,NaN,NaN,What was the group's perspective on how confro...,The group agreed that confronting biases is a ...
12829,Does Gina know this information?,tom:info_accessibility:binary,yes,NaN,"Gina: Claire, I think it's really important to...","Gina: Claire, I think it's really important to...",255-2-1,NaN,accessible,NaN,NaN,What was the group's perspective on how confro...,The group agreed that confronting biases is a ...
12830,Does Sierra know this information?,tom:info_accessibility:binary,yes,NaN,"Gina: Claire, I think it's really important to...","Gina: Claire, I think it's really important to...",255-2-1,NaN,accessible,NaN,NaN,What was the group's perspective on how confro...,The group agreed that confronting biases is a ...
12831,Does Claire know this information?,tom:info_accessibility:binary,yes,NaN,"Gina: Claire, I think it's really important to...","Gina: Claire, I think it's really important to...",255-2-1,NaN,accessible,NaN,NaN,What was the group's perspective on how confro...,The group agreed that confronting biases is a ...

In [5]:
df['question_type'].value_counts()

question_type
tom:answerability:binary                   3571
tom:info_accessibility:binary              3571
tom:belief:inaccessible                     993
tom:belief:inaccessible:multiple-choice     993
fact                                        870
tom:answerability:list                      870
tom:info_accessibility:list                 870
tom:belief:accessible                       547
tom:belief:accessible:multiple-choice       547
Name: count, dtype: int64

In [14]:
df.loc[df["question_type"] == "tom:belief:accessible:multiple-choice"][
    ["context", "question", "correct_answer"]
].values

array([["Gianna: Guys, I've really enjoyed sharing our pet stories, but I need to excuse myself. I need to change clothes for a meeting later. Talk to you later!\nSara: Sure thing, Gianna. Take care!\nJavier: Catch you later, Gianna.\nSara: So Javier, have you ever tried training Bruno?\nJavier: Yes, I did actually. It was a challenge at times, but rewarding nevertheless. How about you? Did you try training Snowflake?\nSara: Oh gosh, trying to train a cat is a whole different ball game. But I did manage to teach her a few commands and tricks. She was quite an intelligent little furball.\nGianna: Hey guys, I'm back, couldn't miss out on more pet stories. Speaking of teaching and training pets, it is amazing how that further strengthens the bond between us and our pets, right?\nSara: Absolutely, Gianna! The fact that they trust us enough to learn from us is really special.\nJavier: I can't agree more. I believe that's one of the ways Bruno conveyed his love and trust towards me. It also gave me a sense of responsibility towards him.\nGianna: Just like Chirpy. Once she began to imitate me, we connected in a way I never imagined. She would repeat words that I was studying for exams and that somehow made studying less stressful.\nJavier: Pets are indeed lifesavers in so many ways.\nSara: They bring so much joy and laughter too into our lives. I mean, imagine a little kitten stuck in a vase! I couldn't have asked for a better stress buster during my college days.\nGianna: Totally, they all are so amazing in their unique ways. It's so nice to have these memories to look back on.",
        "What does Sara believe about Javier's belief regarding who discussed their experiences training their pets, Bruno and Snowflake?\n(a) Sara is unaware about Javier's belief regarding who discussed their experiences training their pets, Bruno and Snowflake.\n(b) Sara believes that Javier thinks they both discussed their experiences training their pets, Bruno and Snowflake.\n\nChoose an answer from above:",
        1],
       ["Christian: So, guys, how do you deal with challenges at your respective jobs?\nJaiden: I believe challenges are opportunities in disguise. They allow us to grow, learn, and evolve. Whenever I'm confronted with a challenge at my job, I take a moment, assess the situation, and then sculpt a strategy for it. For instance, balancing my work and personal life used to be a big challenge for me. However, I learned to set clear boundaries and manage my time more aptly.\nFatima: That's a great approach, Jaiden. I guess for me, the biggest challenge has been dealing with different personalities in my team. Being an introvert, it was especially difficult for me to express my opinions and suggestions. But, I think, over time, I managed to overcome that by observing, learning, and eventually, adopting certain assertive communication strategies.\nChristian: I can totally relate to that, Fatima. In a similar vein, the biggest challenge for me has been to manage stress. I work in a high-pressure environment, and it can get overwhelming at times. However, with the help of regular exercise and meditation, I've been able to manage my stress levels to a considerable extent.\nJaiden: It's great to know that you've confronted your challenges head-on, guys. In fact, these moments make us realize our true potential, and that's really empowering, isn't it?\nFatima: Absolutely, Jaiden—our challenges make us the people we are today, stronger and more resilient.\nChristian: Couldn't agree with you more, guys. These experiences not only shape our professional lives but also have a significant impact on our personal growth. It's always interesting to hear about different perspectives on such matters.\nVeronica: Hey, guys! Just heard the tail end of your conversation. I think work-life balance is indeed a crucial aspect of our lives, isn't it?\nJaiden: Definitely, Veronica! It's like a tightrope walk at times, where you've to maintain your equilibrium between personal and professional life.\nFatima: Agree, Jaiden. I believe setting clear boundaries is necessary to maintain that balance. Isn't it?\nVeronica: Absolutely, Fatima. In my case, it took some time to understand that it's okay to say 'no' sometimes, especially when work expectations are turning unrealistic.\nChristian: Great point, Veronica. Setting limits is a vital part of maintaining mental health. I've noticed that regular exercises and yoga do wonders in de-stressing and keeping myself in equilibrium.\nVeronica: True, Christian. Ultimately, our health and happiness should be our top priority, no matter what profession we are in.\nJaiden: That's an important reminder, Veronica. Often, in the pursuit of professional success, we tend to overlook our personal well-being, which is not healthy.\nFatima: Yeah, striking a balance is the key, which comes with time and lots of practice. I guess we are all lifelong learners in this regard.\nChristian: I couldn't agree more, Fatima. Thanks for sharing your insights, everyone! It's always enriching to have such conversations.\nVeronica: Indeed, Christian. Learning from each other's experiences is the best way to grow.",
        'What does Veronica believe are the strategies that Christian uses to manage stress in a high-pressure work environment?\n(a) Veronica believes that Christian manages stress in a high-pressure work environment by engaging in regular exercises and practicing yoga.\n(b) Veronica does not know the strategies that Christian uses to manage stress in a high-pressure work environment because she was not involved in the conversation when this was discussed.\n\nChoose an answer from above:',
        0],
       ["Christian: So, guys, how do you deal with challenges at your respective jobs?\nJaiden: I believe challenges are opportunities in disguise. They allow us to grow, learn, and evolve. Whenever I'm confronted with a challenge at my job, I take a moment, assess the situation, and then sculpt a strategy for it. For instance, balancing my work and personal life used to be a big challenge for me. However, I learned to set clear boundaries and manage my time more aptly.\nFatima: That's a great approach, Jaiden. I guess for me, the biggest challenge has been dealing with different personalities in my team. Being an introvert, it was especially difficult for me to express my opinions and suggestions. But, I think, over time, I managed to overcome that by observing, learning, and eventually, adopting certain assertive communication strategies.\nChristian: I can totally relate to that, Fatima. In a similar vein, the biggest challenge for me has been to manage stress. I work in a high-pressure environment, and it can get overwhelming at times. However, with the help of regular exercise and meditation, I've been able to manage my stress levels to a considerable extent.\nJaiden: It's great to know that you've confronted your challenges head-on, guys. In fact, these moments make us realize our true potential, and that's really empowering, isn't it?\nFatima: Absolutely, Jaiden—our challenges make us the people we are today, stronger and more resilient.\nChristian: Couldn't agree with you more, guys. These experiences not only shape our professional lives but also have a significant impact on our personal growth. It's always interesting to hear about different perspectives on such matters.\nVeronica: Hey, guys! Just heard the tail end of your conversation. I think work-life balance is indeed a crucial aspect of our lives, isn't it?\nJaiden: Definitely, Veronica! It's like a tightrope walk at times, where you've to maintain your equilibrium between personal and professional life.\nFatima: Agree, Jaiden. I believe setting clear boundaries is necessary to maintain that balance. Isn't it?\nVeronica: Absolutely, Fatima. In my case, it took some time to understand that it's okay to say 'no' sometimes, especially when work expectations are turning unrealistic.\nChristian: Great point, Veronica. Setting limits is a vital part of maintaining mental health. I've noticed that regular exercises and yoga do wonders in de-stressing and keeping myself in equilibrium.\nVeronica: True, Christian. Ultimately, our health and happiness should be our top priority, no matter what profession we are in.\nJaiden: That's an important reminder, Veronica. Often, in the pursuit of professional success, we tend to overlook our personal well-being, which is not healthy.\nFatima: Yeah, striking a balance is the key, which comes with time and lots of practice. I guess we are all lifelong learners in this regard.\nChristian: I couldn't agree more, Fatima. Thanks for sharing your insights, everyone! It's always enriching to have such conversations.\nVeronica: Indeed, Christian. Learning from each other's experiences is the best way to grow.",
        "What does Jaiden believe about Veronica's belief regarding the strategies Christian uses to manage stress in a high-pressure work environment?\n(a) The text provides no information on what Jaiden believes about Veronica's belief regarding the strategies Christian uses to manage stress in a high-pressure work environment. Therefore, it can be stated that Jaiden is unaware about this information.\n(b) Jaiden believes that Veronica is unaware of the strategies Christian uses to manage stress in a high-pressure work environment, because Veronica was not involved in the conversation when this was discussed.\n\nChoose an answer from above:",
        0],
       ...,
       ['Gina: Claire, I think it\'s really important to address personal biases and prejudices. They can unknowingly sabotage our interactions with individuals from different backgrounds.\nClaire: Yeah, absolutely! I completely agree, Gina. We all carry around unconscious biases but it\'s important to be more self-aware and mindful of them. Then only can we break free from our preconceived notions and stereotypes.\nGina: Right. One of the ways I learned to recognize my own biases was through self-reflection. I had to ask myself tough questions like why certain people or situations bothered me. I had to really dig deep and not just chalk things up to “that’s just how I am.”\nClaire: That\'s a great approach. Self-reflection and introspection are powerful tools. I\'ve found that exposing myself to different experiences, cultures, and ways of life has been immensely helpful as well. The more I learn about the world, the more I realize how small my world view used to be.\nGina: That’s insightful, Claire. Exposure really minimizes ignorance. Have you ever read "\nClaire: Blink" by Malcolm Gladwell? He talks a lot about how our brains make snap judgments, and consequently, harbor unconscious biases.\nGina: Yes, I have, it was an insightful read. So, understanding our personal biases helps to make better decisions and connect with others on a deeper level. We need this more in today\'s world to promote diversity and inclusion.\nClaire: True. Once we start acknowledging that biases exist, we can work towards combating them. We need to continuously engage in awareness, acceptance, and action to eradicate our personal prejudices.\nGina: And I think it\'s a continuous, lifelong process. We\'re not perfect, but what matters is that we\'re making the effort to improve ourselves and help create a more empathetic society.\nClaire: Couldn\'t have said it better myself, Gina!\nSierra: Hi Claire, hi Gina! I just wanted to add, from my personal experience, that biases and prejudices really can stunt personal growth. They prevent us from reaching out and learning from others, and create unnecessary barriers between us and the world.\nGina: Absolutely, Sierra. These prejudices act like blinders, making us see a distorted version of reality. When we shed these biases, we allow ourselves to accept and learn from the experiences of others.\nClaire: Yes, and it limits our opportunities too. In my past job, our boss had an unspoken bias against introverts. He assumed they couldn’t be good leaders. But when he retired and a new boss took over who didn\'t have such preconceptions, many introverts, who were indeed great leaders, got the chance to shine.\nSierra: Wrong assumptions can be so damaging. I remember when I moved to a new city, I had this prejudice that people wouldn\'t be friendly. However, when I let go of this preconceived notion, I found warm and kind-hearted individuals everywhere.\nGina: And these biases not only limit us, but also cause harm to others. I think it\'s really important for us to see how our prejudices impact the people around us.\nSierra: Well said, Gina. Reflecting on biases is not only for personal growth, it\'s also about creating a more understanding and accepting society.\nClaire: Absolutely. By challenging these biases, we are not only enriching our own lives but potentially those of the people around us as well. It\'s all about breaking down the walls of misunderstanding and fostering an environment of acceptance.\nBrooke: Hi, Claire, Gina, and Sierra! I saw you folks in deep conversation. Hope I\'m not interrupting anything important. I overheard you discussing prejudices, and it reminded me of a personal encounter.\nGina: Not at all, Brooke. We were actually talking about how important it is to acknowledge our personal biases. Please feel free to share your experience.\nBrooke: Thank you, Gina. Few years back I had a great friend. We connected on many levels but my unconscious bias against her family\'s socio-economic status affected our relationship. It wasn\'t until I confronted my own bias that I realized I was looking at her through a lens of prejudice.\nSierra: I can relate to that, Brooke. It\'s surprising how our own biases can sneak up on us and effect our relationships.\nClaire: Absolutely, Brooke. It takes courage to face our biases, especially when they’re affecting people we care about. By revealing and dealing with them, we grow not only ourselves but also our relationships.\nBrooke: Exactly, Claire. And it wasn\'t an overnight process. It took time and a lot of self-reflection. But the whole experience made me so much more aware of my biases.\nGina: I think it\'s great that you were able to acknowledge and confront your bias, Brooke. It\'s not an easy thing to do. It opens up a chain of self-questioning and self-realization.\nBrooke: Very true, Gina. Imagine how diverse and open-minded we can be if we all choose to confront our biases and prejudices.\nSierra: Absolutely, Brooke. We can indeed build healthy connections and forge stronger relationships by overcoming our biases.\nClaire: Couldn\'t have put it better, Brooke. Acknowledging and overcoming biases is the first step towards building an open, accepting and empathetic society.\nPaisley: Hello everyone, apologies for being late to the conversation. I couldn\'t help but catch the tail-end of what Brooke mentioned about overcoming biases. This is such an essential subject.\nGina: Hi, Paisley. Absolutely, it\'s a conversation we need to engage in more often. So, do you have any thoughts or experiences to share?\nPaisley: Absolutely, Gina. Few years back, I realised that I had a significant bias against people who didn\'t go to college. I believed that they weren\'t as intelligent or dedicated.\nSierra: Paisley, it\'s brave of you to admit that. Many of us do have deep-seated biases like that, even if we\'re not aware of them.\nPaisley: That\'s true, Sierra. What helped me was meeting a colleague who didn\'t go to college and who was easily one of the smartest people I\'ve known. That shook me to my core and made me question my bias.\nClaire: That\'s a great experience, Paisley. Often, it takes real-world experiences to shift our biased perspectives.\nBrooke: Absolutely, Claire. Paisley, your story demonstrates that at times, our biases are just misconceptions. Life experiences are great teachers.\nGina: Well said, Brooke. And Paisley, your journey in overcoming that bias must have been quite life-changing.\nPaisley: Indeed, Gina. Reflecting on it, I am glad I had the opportunity to challenge and overcome my bias. It just helped me create a more fair and inclusive environment around me.\nSierra: It\'s amazing how just one person, one interaction, can completely change our perspectives, isn\'t it?\nClaire: Completely, Sierra. Interaction and exposure to different people and realities really undermine these biases.\nPaisley: That\'s true, Claire. So much of the work in combating bias is about taking the initiative to expose ourselves to diverse experiences and viewpoints.\nBrooke: I think the fact that we\'re even having this conversation is a positive step towards defeating biases. Acknowledging them is the first great stride.\nGina: And continuing to question and challenge them on an ongoing basis, just like all of you shared. Let\'s keep this valuable conversation alive.\nPaisley: Absolutely, Gina. Conversations like these are essential for fostering understanding and empathy amidst diversity.',
        "What does Gina believe are Sierra's thoughts on the effects of the biases and prejudices discussed by the group?\n(a) Gina is unaware of Sierra's thoughts on the effects of the biases and prejudices discussed by the group.\n(b) Gina believes that Sierra thinks the effects of the biases and prejudices discussed by the group can sabotage interactions with individuals from different backgrounds, stunt personal growth, create unnecessary barriers and limit opportunities. Moreover, she thinks Sierra views that they can also negatively affect relationships and create a distorted view of reality, damage through wrong assumptions and cause harm to others. Lastly, Gina believes that Sierra thinks biases and prejudices can restrict the diversity of personal experiences and viewpoints, hence preventing the creation of a fair, inclusive and diverse environment.\n\nChoose an answer from above:",
        1],

In [15]:
df.loc[df["question_type"] == "tom:belief:accessible:multiple-choice"]['correct_answer'].value_counts()

correct_answer
0    289
1    258
Name: count, dtype: int64

In [16]:
df.loc[df["question_type"] == "tom:belief:inaccessible:multiple-choice"][
    "correct_answer"
].value_counts()

correct_answer
1    519
0    474
Name: count, dtype: int64

In [17]:
df.loc[df["question_type"] == "tom:answerability:binary"][
    "correct_answer"
].value_counts()

correct_answer
yes        2372
no          642
no:long     557
Name: count, dtype: int64

In [18]:
df.loc[df["question_type"] == "tom:info_accessibility:binary"][
    "correct_answer"
].value_counts()

correct_answer
yes        2373
no          641
no:long     557
Name: count, dtype: int64

In [20]:
df.loc[df["question_type"] == "tom:answerability:binary"][[
    "question", "correct_answer"
]].head(5).values

array([['Does Gianna know the precise correct answer to this question?',
        'no'],
       ['Does Alondra know the precise correct answer to this question?',
        'no:long'],
       ['Does Sara know the precise correct answer to this question?',
        'yes'],
       ['Does Javier know the precise correct answer to this question?',
        'yes'],
       ['Does Angela know the precise correct answer to this question?',
        'no:long']], dtype=object)

After converting the dataset and storing `train.parquet` and `test.parquet`, check dataset examples

In [1]:
import pandas as pd
df = pd.read_parquet("/home/jiaruil5/social_reasoning_rl/data/fantom/train.parquet")
df

,question,question_type,tom_type,correct_answer,wrong_answer,missed_info_accessibility,context,input_text,set_id,choices_text,choices_list,data_source,prompt,ability,reward_model,extra_info
0,What does Veronica believe about how Fatima ov...,tom:belief:inaccessible:multiple-choice,first-order,(a),Veronica believes that Fatima overcomes the ch...,inaccessible,"Christian: So, guys, how do you deal with chal...","Christian: So, guys, how do you deal with chal...",1-0-0,(a) Veronica does not know or is unaware about...,[(a) Veronica does not know or is unaware abou...,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': '(a)', 'question':...","{'index': 0, 'split': 'train'}"
1,What does Jaiden believe about Veronica's beli...,tom:belief:inaccessible:multiple-choice,second-order:acyclic,(b),Jaiden believes that Veronica thinks Fatima ov...,inaccessible,"Christian: So, guys, how do you deal with chal...","Christian: So, guys, how do you deal with chal...",1-0-0,(a) Jaiden believes that Veronica thinks Fatim...,[(a) Jaiden believes that Veronica thinks Fati...,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': '(b)', 'question':...","{'index': 1, 'split': 'train'}"
2,What does Fatima believe about Veronica's beli...,tom:belief:inaccessible:multiple-choice,second-order:cyclic,(b),Fatima believes that Veronica thinks she overc...,inaccessible,"Christian: So, guys, how do you deal with chal...","Christian: So, guys, how do you deal with chal...",1-0-0,(a) Fatima believes that Veronica thinks she o...,[(a) Fatima believes that Veronica thinks she ...,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': '(b)', 'question':...","{'index': 2, 'split': 'train'}"
3,Does Greyson know the precise correct answer t...,tom:answerability:binary,None,no,None,inaccessible,"Christian: So, guys, how do you deal with chal...","Christian: So, guys, how do you deal with chal...",1-0-0,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'no', 'question': ...","{'index': 3, 'split': 'train'}"
4,Does Veronica know the precise correct answer ...,tom:answerability:binary,None,no,None,inaccessible,"Christian: So, guys, how do you deal with chal...","Christian: So, guys, how do you deal with chal...",1-0-0,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'no', 'question': ...","{'index': 4, 'split': 'train'}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7784,Does Brooke know this information?,tom:info_accessibility:binary,None,yes,None,accessible,"Gina: Claire, I think it's really important to...","Gina: Claire, I think it's really important to...",255-2-1,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'yes', 'question':...","{'index': 7784, 'split': 'train'}"
7785,Does Paisley know this information?,tom:info_accessibility:binary,None,yes,None,accessible,"Gina: Claire, I think it's really important to...","Gina: Claire, I think it's really important to...",255-2-1,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'yes', 'question':...","{'index': 7785, 'split': 'train'}"
7786,Does Gina know this information?,tom:info_accessibility:binary,None,yes,None,accessible,"Gina: Claire, I think it's really important to...","Gina: Claire, I think it's really important to...",255-2-1,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'yes', 'question':...","{'index': 7786, 'split': 'train'}"
7787,Does Sierra know this information?,tom:info_accessibility:binary,None,yes,None,accessible,"Gina: Claire, I think it's really important to...","Gina: Claire, I think it's really important to...",255-2-1,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'yes', 'question':...","{'index': 7787, 'split': 'train'}"
7788,Does Claire know this information?,tom:info_accessibility:binary,None,yes,None,accessible,"Gina: Claire, I think it's really important to...","Gina: Claire, I think it's really important to...",255-2-1,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'yes', 'question':...","{'index': 7788, 'split': 'train'}"

In [2]:
df['question_type'].value_counts()

question_type
tom:answerability:binary                   3202
tom:info_accessibility:binary              3202
tom:belief:inaccessible:multiple-choice     890
tom:belief:accessible:multiple-choice       495
Name: count, dtype: int64

In [3]:
df["correct_answer"].value_counts()

correct_answer
yes    4255
no     2149
(b)     708
(a)     677
Name: count, dtype: int64

In [4]:
df_test = pd.read_parquet("/home/jiaruil5/social_reasoning_rl/data/fantom/test.parquet")
df_test

,question,question_type,tom_type,correct_answer,wrong_answer,missed_info_accessibility,context,input_text,set_id,choices_text,choices_list,data_source,prompt,ability,reward_model,extra_info
0,What does Gianna believe about who discussed t...,tom:belief:inaccessible:multiple-choice,first-order,(b),Gianna believes that Sara and Javier discussed...,inaccessible,"Gianna: Guys, I've really enjoyed sharing our ...","Gianna: Guys, I've really enjoyed sharing our ...",0-0-0,(a) Gianna believes that Sara and Javier discu...,[(a) Gianna believes that Sara and Javier disc...,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': '(b)', 'question':...","{'index': 0, 'split': 'test'}"
1,What does Sara believe about Javier's belief r...,tom:belief:accessible:multiple-choice,second-order:accessible,(b),Sara is unaware about Javier's belief regardin...,accessible,"Gianna: Guys, I've really enjoyed sharing our ...","Gianna: Guys, I've really enjoyed sharing our ...",0-0-0,(a) Sara is unaware about Javier's belief rega...,[(a) Sara is unaware about Javier's belief reg...,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': '(b)', 'question':...","{'index': 1, 'split': 'test'}"
2,Does Gianna know the precise correct answer to...,tom:answerability:binary,None,no,None,inaccessible,"Gianna: Guys, I've really enjoyed sharing our ...","Gianna: Guys, I've really enjoyed sharing our ...",0-0-0,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'no', 'question': ...","{'index': 2, 'split': 'test'}"
3,Does Alondra know the precise correct answer t...,tom:answerability:binary,None,no,None,inaccessible,"Gianna: Guys, I've really enjoyed sharing our ...","Gianna: Guys, I've really enjoyed sharing our ...",0-0-0,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'no', 'question': ...","{'index': 3, 'split': 'test'}"
4,Does Sara know the precise correct answer to t...,tom:answerability:binary,None,yes,None,inaccessible,"Gianna: Guys, I've really enjoyed sharing our ...","Gianna: Guys, I've really enjoyed sharing our ...",0-0-0,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'yes', 'question':...","{'index': 4, 'split': 'test'}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,Does Christian know this information?,tom:info_accessibility:binary,None,yes,None,accessible,"Courtney: It's really nice meeting you both, A...","Courtney: It's really nice meeting you both, A...",254-1-2,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'yes', 'question':...","{'index': 888, 'split': 'test'}"
889,Does Antonio know this information?,tom:info_accessibility:binary,None,yes,None,accessible,"Courtney: It's really nice meeting you both, A...","Courtney: It's really nice meeting you both, A...",254-1-2,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'yes', 'question':...","{'index': 889, 'split': 'test'}"
890,Does Courtney know this information?,tom:info_accessibility:binary,None,yes,None,accessible,"Courtney: It's really nice meeting you both, A...","Courtney: It's really nice meeting you both, A...",254-1-2,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'yes', 'question':...","{'index': 890, 'split': 'test'}"
891,Does Cierra know this information?,tom:info_accessibility:binary,None,yes,None,accessible,"Courtney: It's really nice meeting you both, A...","Courtney: It's really nice meeting you both, A...",254-1-2,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'yes', 'question':...","{'index': 891, 'split': 'test'}"
892,Does Arabella know this information?,tom:info_accessibility:binary,None,yes,None,accessible,"Courtney: It's really nice meeting you both, A...","Courtney: It's really nice meeting you both, A...",254-1-2,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'yes', 'question':...","{'index': 892, 'split': 'test'}"

In [5]:
df_test["question_type"].value_counts()

question_type
tom:answerability:binary                   369
tom:info_accessibility:binary              369
tom:belief:inaccessible:multiple-choice    103
tom:belief:accessible:multiple-choice       52
Name: count, dtype: int64

In [6]:
set(df['context']).intersection(set(df_test['context']))

set()

check prompt length

In [7]:
df

,question,question_type,tom_type,correct_answer,wrong_answer,missed_info_accessibility,context,input_text,set_id,choices_text,choices_list,data_source,prompt,ability,reward_model,extra_info
0,What does Veronica believe about how Fatima ov...,tom:belief:inaccessible:multiple-choice,first-order,(a),Veronica believes that Fatima overcomes the ch...,inaccessible,"Christian: So, guys, how do you deal with chal...","Christian: So, guys, how do you deal with chal...",1-0-0,(a) Veronica does not know or is unaware about...,[(a) Veronica does not know or is unaware abou...,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': '(a)', 'question':...","{'index': 0, 'split': 'train'}"
1,What does Jaiden believe about Veronica's beli...,tom:belief:inaccessible:multiple-choice,second-order:acyclic,(b),Jaiden believes that Veronica thinks Fatima ov...,inaccessible,"Christian: So, guys, how do you deal with chal...","Christian: So, guys, how do you deal with chal...",1-0-0,(a) Jaiden believes that Veronica thinks Fatim...,[(a) Jaiden believes that Veronica thinks Fati...,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': '(b)', 'question':...","{'index': 1, 'split': 'train'}"
2,What does Fatima believe about Veronica's beli...,tom:belief:inaccessible:multiple-choice,second-order:cyclic,(b),Fatima believes that Veronica thinks she overc...,inaccessible,"Christian: So, guys, how do you deal with chal...","Christian: So, guys, how do you deal with chal...",1-0-0,(a) Fatima believes that Veronica thinks she o...,[(a) Fatima believes that Veronica thinks she ...,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': '(b)', 'question':...","{'index': 2, 'split': 'train'}"
3,Does Greyson know the precise correct answer t...,tom:answerability:binary,None,no,None,inaccessible,"Christian: So, guys, how do you deal with chal...","Christian: So, guys, how do you deal with chal...",1-0-0,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'no', 'question': ...","{'index': 3, 'split': 'train'}"
4,Does Veronica know the precise correct answer ...,tom:answerability:binary,None,no,None,inaccessible,"Christian: So, guys, how do you deal with chal...","Christian: So, guys, how do you deal with chal...",1-0-0,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'no', 'question': ...","{'index': 4, 'split': 'train'}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7784,Does Brooke know this information?,tom:info_accessibility:binary,None,yes,None,accessible,"Gina: Claire, I think it's really important to...","Gina: Claire, I think it's really important to...",255-2-1,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'yes', 'question':...","{'index': 7784, 'split': 'train'}"
7785,Does Paisley know this information?,tom:info_accessibility:binary,None,yes,None,accessible,"Gina: Claire, I think it's really important to...","Gina: Claire, I think it's really important to...",255-2-1,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'yes', 'question':...","{'index': 7785, 'split': 'train'}"
7786,Does Gina know this information?,tom:info_accessibility:binary,None,yes,None,accessible,"Gina: Claire, I think it's really important to...","Gina: Claire, I think it's really important to...",255-2-1,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'yes', 'question':...","{'index': 7786, 'split': 'train'}"
7787,Does Sierra know this information?,tom:info_accessibility:binary,None,yes,None,accessible,"Gina: Claire, I think it's really important to...","Gina: Claire, I think it's really important to...",255-2-1,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'yes', 'question':...","{'index': 7787, 'split': 'train'}"
7788,Does Claire know this information?,tom:info_accessibility:binary,None,yes,None,accessible,"Gina: Claire, I think it's really important to...","Gina: Claire, I think it's really important to...",255-2-1,None,None,fantom,[{'content': 'A conversation between User and ...,fantom,"{'ground_truth': {'answer': 'yes', 'question':...","{'index': 7788, 'split': 'train'}"

In [8]:
import numpy as np
from transformers import AutoTokenizer

# Load the tokenizer
model_name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)


def count_tokens(prompt_entry):
    if isinstance(prompt_entry, np.ndarray) and len(prompt_entry) > 0:
        prompt_list = prompt_entry.tolist()  # Convert NumPy array to list
        if (
            isinstance(prompt_list, list)
            and isinstance(prompt_list[0], dict)
            and "content" in prompt_list[0]
        ):
            text = prompt_list[0]["content"]  # Extract the 'content' text
            tokenized_output = tokenizer(text, return_tensors="pt")
            return tokenized_output["input_ids"].shape[1]  # Get token count
    return None  # Return None if input format is incorrect


# Apply token counting to DataFrame
df["num_tokens"] = df["prompt"].apply(count_tokens)

In [9]:
df_test["num_tokens"] = df_test["prompt"].apply(count_tokens)

In [10]:
df['num_tokens'].max()

1902

In [11]:
df_test["num_tokens"].max()

1913

prompt length should be set to 2048